export const EVENT_APPLIC_CLOSE_ACTIVE = 'EVENT_APPLIC_CLOSE_ACTIVE';
export const EVENT_APPLIC_NEW_ANEW_OPEN = 'APPLIC_NEW_ANEW_OPEN';
export const EVENT_APPLIC_NEW_CLOSE = 'APPLIC_NEW_CLOSE';
export const EVENT_APPLIC_CLICK_QUERY = 'APPLIC_CLICK_QUERY';
